# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: s3cr3t

  app:
    build: .
    environment:
      - DB_HOST=db
      - DB_PASSWORD={"username":"postgres","password":"s3cr3t"}
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: ["python", "main.py"]